version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

  api:
    container_name: api
    build:
      context: .
      dockerfile: RabbitAdoption.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBIT_DB_PATH=/app/Database/rabbitadoption.db
    volumes:
      - ./Database:/app/Database

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: RabbitAdoption.Worker/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBIT_DB_PATH=/app/Database/rabbitadoption.db
    volumes:
      - ./Database:/app/Database
