// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RabbitAdoption.Infrastructure;

#nullable disable

namespace RabbitAdoption.Infrastructure.Migrations
{
    [DbContext(typeof(RabbitAdoptionDbContext))]
    partial class RabbitAdoptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RabbitAdoption.Domain.AdoptionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdopterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearsRabbitExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AdoptionRequests");
                });

            modelBuilder.Entity("RabbitAdoption.Domain.Rabbit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdopted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Size", "Color", "Age");

                    b.ToTable("Rabbits");
                });

            modelBuilder.Entity("RabbitAdoption.Domain.AdoptionRequest", b =>
                {
                    b.OwnsOne("RabbitAdoption.Domain.RabbitPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("AdoptionRequestId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AgeRange")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Breed")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Size")
                                .HasColumnType("TEXT");

                            b1.HasKey("AdoptionRequestId");

                            b1.ToTable("AdoptionRequests");

                            b1.WithOwner()
                                .HasForeignKey("AdoptionRequestId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
